modLoader="javafml"
loaderVersion="[4,)"
license="MIT License"

[[mods]]
modId="muchof_biomes"
version="1.1.0"
displayName="Much'of Biomes"
displayURL="https://mcreator.net"
credits="a mod that adds more biomes to the game"
authors="CorrelationWX"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "muchof_biomes.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.muchof_biomes]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.190,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.muchof_biomes]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration